[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"  # This is currently the latest for Mainnet
solc_version = "0.8.23" # Use the latest stable Solidity version
optimizer = true
optimizer_runs = 200
